# Generated by Django 5.0.6 on 2024-05-11 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('measurement_unit', models.CharField(choices=[('gCO2eq/kWh', 'Gco2Eq Kwh'), ('kt', 'Kt'), ('MtCO2e', 'Mt Co2E'), ('Mg', 'Mg')], default='gCO2eq/kWh', max_length=20)),
                ('high_measurement_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('med_measurement_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_measurement_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('off_measurement_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemtrakapp.organization')),
            ],
        ),
    ]
