# Generated by Django 5.0.6 on 2024-05-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemtrakapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitter',
            name='is_compensator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emitter',
            name='measurement_unit',
            field=models.CharField(choices=[('gCO2eq/kWh', 'Gco2Eq Kwh'), ('kt', 'Kt'), ('MtCO2e', 'Mt Co2E'), ('Mg', 'Mg')], default='MtCO2e', max_length=20),
        ),
    ]
