# Generated by Django 5.0.6 on 2024-05-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemtrakapp', '0002_emitter_is_compensator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitter',
            name='external_id',
            field=models.CharField(default='unk', max_length=255),
            preserve_default=False,
        ),
    ]
