# Generated by Django 5.0.6 on 2024-05-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemtrakapp', '0003_emitter_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emitter',
            name='external_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
